### ISSUE TITLE
Sprint 8 Review

### ISSUE THREAD

**Issue by katherine-van-der-ploeg** [thestormtroopers/web-app#38]
In this sprint, we needed to finalize any details in the coded web application. Minus a couple technical difficulties, we were able to finish the web application.

**Comment by katherine-van-der-ploeg** [comment]
@thomasjbradley

**Comment by katherine-van-der-ploeg** [comment]
Overall, this week was a little stressful just finishing the app. Because of the git hub difficulties it was hard to continue work but once it was solved it was easy completing the app. I'm very happy it is done and thank my co workers for helping to complete it as well!!

**Comment by taylorion** [comment]
This week was pretty stressful in terms of completing the web app, but I feel that we really came together as a group and completed what we set out to with pretty good execution!! I'm happy with what we created in our time as a group.

**Comment by emnemdesign** [comment]
I agree with Orion this week was stressful considering the fact that github messed up a bit, but I am proud that my group was able to keep it together and work towards a job well done.
